In [2]:
import yfinance as yf
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv('../Data/OPTSTK_RELIANCE_CE_01-Jan-2025_TO_31-Mar-2025.csv')
data.columns = data.columns.str.strip()
data.tail()

,Symbol,Date,Expiry,Option type,Strike Price,Open,High,Low,Close,LTP,Settle Price,No. of contracts,Turnover * in ₹ Lakhs,Premium Turnover ** in ₹ Lakhs,Open Int,Change in OI,Underlying Value
6910,RELIANCE,01-Jan-2025,30-Jan-2025,CE,1190.0,47.65,54.55,46.00,51.55,52.05,51.55,233.00,1443.48,57.13,86500.00,-7000.00,1221.25
6911,RELIANCE,01-Jan-2025,30-Jan-2025,CE,1380.0,0.95,1.30,0.90,1.05,1.05,1.05,314.00,2168.24,1.64,459000.00,30500.00,1221.25
6912,RELIANCE,01-Jan-2025,30-Jan-2025,CE,1390.0,0.90,0.95,0.80,0.85,0.85,0.85,107.00,744.12,0.47,142500.00,13500.00,1221.25
6913,RELIANCE,01-Jan-2025,30-Jan-2025,CE,1200.0,40.45,47.25,39.10,44.40,44.95,44.40,4269.00,26541.49,927.49,2104000.00,-179000.00,1221.25
6914,RELIANCE,01-Jan-2025,30-Jan-2025,CE,1210.0,35.05,40.00,32.75,37.45,38.00,37.45,5339.00,33256.25,955.30,3150500.00,430500.00,1221.25

In [4]:
data = data.iloc[::-1]
data.tail()

,Symbol,Date,Expiry,Option type,Strike Price,Open,High,Low,Close,LTP,Settle Price,No. of contracts,Turnover * in ₹ Lakhs,Premium Turnover ** in ₹ Lakhs,Open Int,Change in OI,Underlying Value
4,RELIANCE,28-Mar-2025,29-May-2025,CE,1160.0,-,-,-,99.40,-,134.35,-,-,-,-,-,1275.1
3,RELIANCE,28-Mar-2025,29-May-2025,CE,1300.0,42.20,45.35,34.75,36.90,35.95,36.90,1914.00,12815.13,374.13,1238000.00,307000.00,1275.1
2,RELIANCE,28-Mar-2025,29-May-2025,CE,1480.0,-,-,-,5.45,-,3.40,-,-,-,-,-,1275.1
1,RELIANCE,28-Mar-2025,29-May-2025,CE,1290.0,48.55,49.70,48.05,49.70,49.70,45.60,6.00,40.17,1.47,3000.00,3000.00,1275.1
0,RELIANCE,28-Mar-2025,29-May-2025,CE,1140.0,-,-,-,110.00,110.00,151.95,-,-,-,2500.00,-,1275.1

In [5]:
data.columns

Index(['Symbol', 'Date', 'Expiry', 'Option type', 'Strike Price', 'Open',
       'High', 'Low', 'Close', 'LTP', 'Settle Price', 'No. of contracts',
       'Turnover * in  ₹ Lakhs', 'Premium Turnover ** in   ₹ Lakhs',
       'Open Int', 'Change in OI', 'Underlying Value'],
      dtype='object')

In [6]:
S = data.drop_duplicates(subset="Date")[['Date', 'Underlying Value']]
S.head(10)

             Date  Underlying Value
6914  01-Jan-2025           1221.25
6813  02-Jan-2025           1241.80
6712  03-Jan-2025           1251.15
6605  06-Jan-2025           1218.00
6500  07-Jan-2025           1240.85
6395  08-Jan-2025           1265.50
6290  09-Jan-2025           1254.75
6183  10-Jan-2025           1241.90
6076  13-Jan-2025           1239.85
5969  14-Jan-2025           1238.75

In [8]:
S.to_csv("../S_path.csv", index=False)

In [9]:
data.head()

,Symbol,Date,Expiry,Option type,Strike Price,Open,High,Low,Close,LTP,Settle Price,No. of contracts,Turnover * in ₹ Lakhs,Premium Turnover ** in ₹ Lakhs,Open Int,Change in OI,Underlying Value
6914,RELIANCE,01-Jan-2025,30-Jan-2025,CE,1210.0,35.05,40.00,32.75,37.45,38.00,37.45,5339.00,33256.25,955.30,3150500.00,430500.00,1221.25
6913,RELIANCE,01-Jan-2025,30-Jan-2025,CE,1200.0,40.45,47.25,39.10,44.40,44.95,44.40,4269.00,26541.49,927.49,2104000.00,-179000.00,1221.25
6912,RELIANCE,01-Jan-2025,30-Jan-2025,CE,1390.0,0.90,0.95,0.80,0.85,0.85,0.85,107.00,744.12,0.47,142500.00,13500.00,1221.25
6911,RELIANCE,01-Jan-2025,30-Jan-2025,CE,1380.0,0.95,1.30,0.90,1.05,1.05,1.05,314.00,2168.24,1.64,459000.00,30500.00,1221.25
6910,RELIANCE,01-Jan-2025,30-Jan-2025,CE,1190.0,47.65,54.55,46.00,51.55,52.05,51.55,233.00,1443.48,57.13,86500.00,-7000.00,1221.25

In [10]:
C = data[['Date', 'Expiry', 'Strike Price', 'Close']].copy()
C.head()

             Date       Expiry  Strike Price  Close
6914  01-Jan-2025  30-Jan-2025        1210.0  37.45
6913  01-Jan-2025  30-Jan-2025        1200.0  44.40
6912  01-Jan-2025  30-Jan-2025        1390.0   0.85
6911  01-Jan-2025  30-Jan-2025        1380.0   1.05
6910  01-Jan-2025  30-Jan-2025        1190.0  51.55

In [11]:
# C['Close'] = C['Close'].replace('-', np.nan)
C = C[C["Close"] != "-"].copy()
C.to_csv("../C_grid.csv", index=False)

In [12]:
r = pd.read_csv('../Data/INDIR3TIB01STM.csv')
r['observation_date'] = pd.to_datetime(r['observation_date']).dt.strftime("%d-%b-%Y")
r.head()

  observation_date  INDIR3TIB01STM
0      01-Nov-2011        8.868967
1      01-Dec-2011        8.553580
2      01-Jan-2012        8.614225
3      01-Feb-2012        8.917875
4      01-Mar-2012        9.022660

In [13]:
r.to_csv('../r_path.csv', index=False)