In [12]:
import yfinance as yf
import numpy as np
import pandas as pd

In [13]:
data = pd.read_csv('../Data/OPTSTK_RELIANCE_CE_01-Jan-2025_TO_02-Jan-2025.csv')
data.columns = data.columns.str.strip()
data.tail()

,Symbol,Date,Expiry,Option type,Strike Price,Open,High,Low,Close,LTP,Settle Price,No. of contracts,Turnover * in ₹ Lakhs,Premium Turnover ** in ₹ Lakhs,Open Int,Change in OI,Underlying Value
197,RELIANCE,01-Jan-2025,27-Mar-2025,CE,1240.0,-,-,-,62.75,-,52.50,-,-,-,-,-,1221.25
198,RELIANCE,01-Jan-2025,27-Mar-2025,CE,1360.0,-,-,-,23.20,-,14.90,-,-,-,-,-,1221.25
199,RELIANCE,01-Jan-2025,27-Mar-2025,CE,1120.0,-,-,-,135.80,-,130.00,-,-,-,-,-,1221.25
200,RELIANCE,01-Jan-2025,27-Mar-2025,CE,1140.0,-,-,-,121.30,-,114.40,-,-,-,-,-,1221.25
201,RELIANCE,01-Jan-2025,27-Mar-2025,CE,1260.0,-,-,-,53.95,-,43.65,-,-,-,-,-,1221.25

In [14]:
data = data.iloc[::-1]
data.tail()

,Symbol,Date,Expiry,Option type,Strike Price,Open,High,Low,Close,LTP,Settle Price,No. of contracts,Turnover * in ₹ Lakhs,Premium Turnover ** in ₹ Lakhs,Open Int,Change in OI,Underlying Value
4,RELIANCE,02-Jan-2025,27-Feb-2025,CE,1140.0,-,-,-,165.40,-,120.60,-,-,-,-,-,1241.8
3,RELIANCE,02-Jan-2025,27-Feb-2025,CE,1270.0,30.00,30.10,30.00,30.00,30.00,36.25,4.00,26.00,0.60,2000.00,500.00,1241.8
2,RELIANCE,02-Jan-2025,27-Feb-2025,CE,1130.0,-,-,-,116.05,-,129.20,-,-,-,-,-,1241.8
1,RELIANCE,02-Jan-2025,27-Feb-2025,CE,1400.0,4.95,6.20,4.70,5.95,5.90,5.95,521.00,3661.59,14.59,1012500.00,104000.00,1241.8
0,RELIANCE,02-Jan-2025,27-Feb-2025,CE,1260.0,30.55,38.75,29.55,37.25,36.50,37.25,75.00,485.66,13.16,127500.00,-2000.00,1241.8

In [15]:
data.columns

Index(['Symbol', 'Date', 'Expiry', 'Option type', 'Strike Price', 'Open',
       'High', 'Low', 'Close', 'LTP', 'Settle Price', 'No. of contracts',
       'Turnover * in  ₹ Lakhs', 'Premium Turnover ** in   ₹ Lakhs',
       'Open Int', 'Change in OI', 'Underlying Value'],
      dtype='object')

In [16]:
S = data.drop_duplicates(subset="Date")[['Date', 'Underlying Value']]
S.head(10)

            Date  Underlying Value
201  01-Jan-2025           1221.25
100  02-Jan-2025           1241.80

In [17]:
S.to_csv("../S_path.csv", index=False)

In [18]:
data.head()

,Symbol,Date,Expiry,Option type,Strike Price,Open,High,Low,Close,LTP,Settle Price,No. of contracts,Turnover * in ₹ Lakhs,Premium Turnover ** in ₹ Lakhs,Open Int,Change in OI,Underlying Value
201,RELIANCE,01-Jan-2025,27-Mar-2025,CE,1260.0,-,-,-,53.95,-,43.65,-,-,-,-,-,1221.25
200,RELIANCE,01-Jan-2025,27-Mar-2025,CE,1140.0,-,-,-,121.30,-,114.40,-,-,-,-,-,1221.25
199,RELIANCE,01-Jan-2025,27-Mar-2025,CE,1120.0,-,-,-,135.80,-,130.00,-,-,-,-,-,1221.25
198,RELIANCE,01-Jan-2025,27-Mar-2025,CE,1360.0,-,-,-,23.20,-,14.90,-,-,-,-,-,1221.25
197,RELIANCE,01-Jan-2025,27-Mar-2025,CE,1240.0,-,-,-,62.75,-,52.50,-,-,-,-,-,1221.25

In [19]:
C = data[['Date', 'Expiry', 'Strike Price', 'Close']].copy()
C.head()

            Date       Expiry  Strike Price   Close
201  01-Jan-2025  27-Mar-2025        1260.0   53.95
200  01-Jan-2025  27-Mar-2025        1140.0  121.30
199  01-Jan-2025  27-Mar-2025        1120.0  135.80
198  01-Jan-2025  27-Mar-2025        1360.0   23.20
197  01-Jan-2025  27-Mar-2025        1240.0   62.75

In [20]:
# C['Close'] = C['Close'].replace('-', np.nan)
C = C[C["Close"] != "-"].copy()
C.to_csv("../C_grid.csv", index=False)

In [21]:
r = pd.read_csv('../Data/INDIR3TIB01STM.csv')
r['observation_date'] = pd.to_datetime(r['observation_date']).dt.strftime("%d-%b-%Y")
r.head()

  observation_date  INDIR3TIB01STM
0      01-Nov-2011        8.868967
1      01-Dec-2011        8.553580
2      01-Jan-2012        8.614225
3      01-Feb-2012        8.917875
4      01-Mar-2012        9.022660

In [22]:
r.to_csv('../r_path.csv', index=False)