In [26]:
import yfinance as yf
import numpy as np
import pandas as pd

In [27]:
data = pd.read_csv('../Data/OPTSTK_RELIANCE_CE_01-Jan-2025_TO_08-Jan-2025.csv')
data.columns = data.columns.str.strip()
data.tail()

,Symbol,Date,Expiry,Option type,Strike Price,Open,High,Low,Close,LTP,Settle Price,No. of contracts,Turnover * in ₹ Lakhs,Premium Turnover ** in ₹ Lakhs,Open Int,Change in OI,Underlying Value
619,RELIANCE,01-Jan-2025,27-Feb-2025,CE,1200.0,58.00,63.75,57.40,60.85,60.65,60.85,88.00,554.70,26.70,125500.00,4000.00,1221.25
620,RELIANCE,01-Jan-2025,27-Feb-2025,CE,1020.0,-,-,-,271.30,-,212.45,-,-,-,-,-,1221.25
621,RELIANCE,01-Jan-2025,27-Feb-2025,CE,1040.0,-,-,-,252.60,-,193.10,-,-,-,-,-,1221.25
622,RELIANCE,01-Jan-2025,27-Feb-2025,CE,1210.0,55.10,55.10,55.10,55.10,55.10,55.40,1.00,6.33,0.28,-,-500.00,1221.25
623,RELIANCE,01-Jan-2025,27-Feb-2025,CE,1220.0,46.10,51.25,45.50,49.50,49.65,49.50,87.00,551.70,21.00,58500.00,7500.00,1221.25

In [28]:
data = data.iloc[::-1]
data.tail()

,Symbol,Date,Expiry,Option type,Strike Price,Open,High,Low,Close,LTP,Settle Price,No. of contracts,Turnover * in ₹ Lakhs,Premium Turnover ** in ₹ Lakhs,Open Int,Change in OI,Underlying Value
4,RELIANCE,08-Jan-2025,27-Feb-2025,CE,1130.0,-,-,-,116.05,-,148.95,-,-,-,-,-,1265.5
3,RELIANCE,08-Jan-2025,27-Feb-2025,CE,1270.0,35.30,46.05,35.30,43.10,43.00,43.10,104.00,682.58,22.18,32000.00,24000.00,1265.5
2,RELIANCE,08-Jan-2025,27-Feb-2025,CE,1120.0,-,-,-,170.00,170.00,158.20,-,-,-,500.00,-,1265.5
1,RELIANCE,08-Jan-2025,27-Feb-2025,CE,1400.0,5.45,7.60,5.45,7.25,7.05,7.25,1380.00,9707.87,47.87,1222500.00,50000.00,1265.5
0,RELIANCE,08-Jan-2025,27-Feb-2025,CE,1260.0,39.75,51.75,39.75,48.50,48.00,48.50,400.00,2616.14,96.14,157500.00,10500.00,1265.5

In [29]:
data.columns

Index(['Symbol', 'Date', 'Expiry', 'Option type', 'Strike Price', 'Open',
       'High', 'Low', 'Close', 'LTP', 'Settle Price', 'No. of contracts',
       'Turnover * in  ₹ Lakhs', 'Premium Turnover ** in   ₹ Lakhs',
       'Open Int', 'Change in OI', 'Underlying Value'],
      dtype='object')

In [30]:
S = data.drop_duplicates(subset="Date")[['Date', 'Underlying Value']]
S.head(10)

            Date  Underlying Value
623  01-Jan-2025           1221.25
522  02-Jan-2025           1241.80
421  03-Jan-2025           1251.15
314  06-Jan-2025           1218.00
209  07-Jan-2025           1240.85
104  08-Jan-2025           1265.50

In [31]:
S.to_csv("../S_path.csv", index=False)

In [32]:
data.head()

,Symbol,Date,Expiry,Option type,Strike Price,Open,High,Low,Close,LTP,Settle Price,No. of contracts,Turnover * in ₹ Lakhs,Premium Turnover ** in ₹ Lakhs,Open Int,Change in OI,Underlying Value
623,RELIANCE,01-Jan-2025,27-Feb-2025,CE,1220.0,46.10,51.25,45.50,49.50,49.65,49.50,87.00,551.70,21.00,58500.00,7500.00,1221.25
622,RELIANCE,01-Jan-2025,27-Feb-2025,CE,1210.0,55.10,55.10,55.10,55.10,55.10,55.40,1.00,6.33,0.28,-,-500.00,1221.25
621,RELIANCE,01-Jan-2025,27-Feb-2025,CE,1040.0,-,-,-,252.60,-,193.10,-,-,-,-,-,1221.25
620,RELIANCE,01-Jan-2025,27-Feb-2025,CE,1020.0,-,-,-,271.30,-,212.45,-,-,-,-,-,1221.25
619,RELIANCE,01-Jan-2025,27-Feb-2025,CE,1200.0,58.00,63.75,57.40,60.85,60.65,60.85,88.00,554.70,26.70,125500.00,4000.00,1221.25

In [33]:
C = data[['Date', 'Expiry', 'Strike Price', 'Close']].copy()
C.head()

            Date       Expiry  Strike Price   Close
623  01-Jan-2025  27-Feb-2025        1220.0   49.50
622  01-Jan-2025  27-Feb-2025        1210.0   55.10
621  01-Jan-2025  27-Feb-2025        1040.0  252.60
620  01-Jan-2025  27-Feb-2025        1020.0  271.30
619  01-Jan-2025  27-Feb-2025        1200.0   60.85

In [34]:
# C['Close'] = C['Close'].replace('-', np.nan)
C = C[C["Close"] != "-"].copy()
C.to_csv("../C_grid.csv", index=False)

In [35]:
r = pd.read_csv('../Data/INDIR3TIB01STM.csv')
r['observation_date'] = pd.to_datetime(r['observation_date']).dt.strftime("%d-%b-%Y")
r.head()

  observation_date  INDIR3TIB01STM
0      01-Nov-2011        8.868967
1      01-Dec-2011        8.553580
2      01-Jan-2012        8.614225
3      01-Feb-2012        8.917875
4      01-Mar-2012        9.022660

In [36]:
r.to_csv('../r_path.csv', index=False)