In [41]:
import numpy as np
import pandas as pd

In [42]:
data = pd.read_csv('../Data_Output/C_data.csv')

data.columns = data.columns.str.strip()
data.head()

,date,expiry date,strike,maturity (years),rate,underlying,call option price,implied vol
0,09-Mar-2026,13-Mar-2026,80.0,0.010959,3.0,100.0,20.026300,0.281248
1,09-Mar-2026,13-Mar-2026,85.0,0.010959,3.0,100.0,15.027900,0.238346
2,09-Mar-2026,13-Mar-2026,90.0,0.010959,3.0,100.0,10.029600,0.225597
3,09-Mar-2026,13-Mar-2026,95.0,0.010959,3.0,100.0,5.038740,0.212658
4,09-Mar-2026,13-Mar-2026,100.0,0.010959,3.0,100.0,0.849889,0.199578

In [43]:
S = data.drop_duplicates(subset="date")[['date', 'underlying']]
S.head(10)

             date  underlying
0     09-Mar-2026     100.000
151   10-Mar-2026     100.910
304   11-Mar-2026     100.204
452   12-Mar-2026     100.391
605   13-Mar-2026     101.428
758   16-Mar-2026     101.435
908   17-Mar-2026     100.873
1059  18-Mar-2026     100.882
1212  19-Mar-2026     100.730
1364  20-Mar-2026     100.529

In [44]:
S.to_csv("../Data_Output/S_path.csv", index=False)

In [45]:
C = data[['date', 'expiry date', 'strike', 'call option price']].copy()
C.head()

          date  expiry date  strike  call option price
0  09-Mar-2026  13-Mar-2026    80.0          20.026300
1  09-Mar-2026  13-Mar-2026    85.0          15.027900
2  09-Mar-2026  13-Mar-2026    90.0          10.029600
3  09-Mar-2026  13-Mar-2026    95.0           5.038740
4  09-Mar-2026  13-Mar-2026   100.0           0.849889

In [46]:
C.to_csv("../Data_Output/C_grid.csv", index=False)

In [47]:
imp_vol = data[['date', 'expiry date', 'strike', 'implied vol']].copy()
imp_vol.head()

          date  expiry date  strike  implied vol
0  09-Mar-2026  13-Mar-2026    80.0     0.281248
1  09-Mar-2026  13-Mar-2026    85.0     0.238346
2  09-Mar-2026  13-Mar-2026    90.0     0.225597
3  09-Mar-2026  13-Mar-2026    95.0     0.212658
4  09-Mar-2026  13-Mar-2026   100.0     0.199578

In [48]:
imp_vol.to_csv("../Data_Output/vol_grid.csv", index=False)

In [49]:
r = data.drop_duplicates(subset="date")[['date', 'rate']]
r.head(10)

             date     rate
0     09-Mar-2026  3.00000
151   10-Mar-2026  2.98318
304   11-Mar-2026  2.92148
452   12-Mar-2026  2.93391
605   13-Mar-2026  2.93987
758   16-Mar-2026  2.94585
908   17-Mar-2026  2.95844
1059  18-Mar-2026  3.06076
1212  19-Mar-2026  2.98118
1364  20-Mar-2026  2.98109

In [50]:
r.to_csv('../Data_Output/r_path.csv', index=False)